export const PRICES_DATA = [
  {
    id: 1,
    title: 'Landing',
    price: 'FROM $1000',
    time: 'FROM 7 BUSINESS DAYS',
    description:
      'A PROMO PAGE OR LANDING PAGE WILL BE SUITABLE FOR SELLING A SMALL NUMBER OF PRODUCTS OR SERVICES. INCLUDES: DESIGN, BUILDING, BASIC SEO OPTIMIZATION.',
  },
  {
    id: 2,
    title: 'Website',
    price: 'FROM $1200',
    time: 'FROM 7 BUSINESS DAYS',
    description:
      'A MULTI-PAGE WEBSITE THAT WILL REPRESENT THE COMPANY, ITS PRODUCTS, OR SERVICE. INCLUDES: DESIGN, BUILDING, BASIC SEO OPTIMIZATION.',
  },
  {
    id: 3,
    title: 'Shop',
    price: 'FROM $2000',
    time: 'FROM 30 BUSINESS DAYS',
    description:
      'A STORE WILL WORK FOR A BUSINESS AND PROVIDE A WIDE VARIETY OF FUNCTIONS: A SHOPPING CART, ONLINE PAYMENTS, AND AN INTERNAL CRM SYSTEM. INCLUDES: DESIGN, BUILDING, BASIC SEO OPTIMIZATION.',
  },
  {
    id: 4,
    title: 'Mobile App',
    price: 'FROM $2000',
    time: 'FROM 30 BUSINESS DAYS',
    description:
      'APP MOBILE WILL WORK FOR A BUSINESS AND PROVIDE A WIDE VARIETY OF FUNCTIONS: A SHOPPING CART, ONLINE PAYMENTS, AND AN INTERNAL CRM SYSTEM. INCLUDES: DESIGN, BUILDING, BASIC SEO OPTIMIZATION.',
  },
];
