export const PROCESS_DATA = [
  {
    id: 1,
    title: 'Creation Time',
    description:
      'THE CREATION OF A WEBSITE ON TILDA TAKES LESS TIME THAN A WEBSITE WRITTEN IN CODE. IT IS AN EXCELLENT OPPORTUNITY IF YOU NEED TO IMPLEMENT YOUR BUSINESS IDEAS QUICKLY WITH THE SAME QUALITY.',
  },
  {
    id: 2,
    title: 'Price',
    description:
      'THE PRICE FOR A SITE WRITTEN IN CODE STARTS FROM 1000€, WHILE A SINGLE-PAGE SITE ON TILDA WILL COST FROM 500€.',
  },
  {
    id: 3,
    title: 'Convenience',
    description:
      'MANAGING A WEBSITE ON TILDA IS EASIER TO UNDERSTAND THAN EDITING A WEBSITE WRITTEN IN CODE. YOU CAN EASILY REMOVE AND ADD BLOCKS, CHANGE THE STRUCTURE.',
  },
];
